name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    tags:
      - '*production*'
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: get_tag_name
        run: echo Tag_Name=$(echo ${GITHUB_REF} | awk -F/ '{print $3}') >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.get_tag_name.outputs.Tag_Name }}
